// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sources": {
            "get": {
                "tags": [
                    "источники"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Source"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "источники"
                ],
                "parameters": [
                    {
                        "description": "источник",
                        "name": "source",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Source"
                        }
                    }
                ],
                "responses": {}
            },
            "patch": {
                "tags": [
                    "источники"
                ],
                "parameters": [
                    {
                        "description": "источник",
                        "name": "source",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Source"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/sources/drivers": {
            "get": {
                "tags": [
                    "источники"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sources/{id}": {
            "get": {
                "tags": [
                    "источники"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "идентификатор источника",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Source"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "источники"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "идентификатор источника",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "entity.Source": {
            "type": "object",
            "properties": {
                "connected": {
                    "type": "boolean"
                },
                "databaseName": {
                    "type": "string"
                },
                "driver": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
