definitions:
  entity.Source:
    properties:
      connected:
        type: boolean
      databaseName:
        type: string
      driver:
        type: string
      host:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
      port:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /sources:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Source'
            type: array
      tags:
      - источники
    patch:
      parameters:
      - description: источник
        in: body
        name: source
        required: true
        schema:
          $ref: '#/definitions/entity.Source'
      responses: {}
      tags:
      - источники
    post:
      parameters:
      - description: источник
        in: body
        name: source
        required: true
        schema:
          $ref: '#/definitions/entity.Source'
      responses: {}
      tags:
      - источники
  /sources/{id}:
    delete:
      parameters:
      - description: идентификатор источника
        in: path
        name: id
        required: true
        type: string
      responses: {}
      tags:
      - источники
    get:
      parameters:
      - description: идентификатор источника
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Source'
      tags:
      - источники
  /sources/drivers:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      tags:
      - источники
swagger: "2.0"
